#!/usr/bin/env python3
"""
verify-no-verbatim.py — gate CI para o pacote consumer-facing.

Assert que NENHUM verbatim de proprietary-license-v1 está presente no
pacote <pkg_dir>. Se detectar, exit ≠ 0.

Uso:
    python3 verify-no-verbatim.py --package <pkg_dir>
    python3 verify-no-verbatim.py --package <pkg_dir> --json

Exit codes:
    0 = PACOTE LIMPO (sem verbatim)
    1 = ERRO DE USO
    2 = VERBATIM DETECTADO (gate falhou)

Este é o gate mandatório antes de qualquer rsync / git push / cp para time externo.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
from typing import NamedTuple


# Padrões EXATAMENTE iguais aos de sanitize.py — se sanitize mudou, este aqui
# deve mudar em paralelo.
PATTERNS = {
    "PATH_VERBATIM": re.compile(
        r"\b addons/[\w_-]+(/[\w_-]+)*\.(?:py|xml|js|csv|json)"
        r"| \b [\w-]+/[\w-]+\.py:\d+"
        r"| \b [\w-]+_view\.xml"
        r"| \b i18n/[\w_]+\.po"
        r"| \b static/[\w/.-]+\.(?:js|css|png|svg)",
        re.VERBOSE,
    ),
    "IMPORT_VERBATIM": re.compile(
        r"^\s*(?:from|import)\s+odoo(?:\.addons\.[\w_-]+)?(?:\.[\w_]+)*[\w.,\s*]*$",
        re.MULTILINE,
    ),
    "FUNCTION_SIG": re.compile(
        r"^(?P<indent>[\t ]*)(?:async\s+)?def\s+(?P<name>\w+)\s*\((?P<args>.*?)\)\s*(?:->\s*[^:]+?)?\s*:",
        re.MULTILINE | re.DOTALL,
    ),
    "CLASS_NAME": re.compile(
        r"^\s*class\s+([A-Z]\w*(?:View|Template|Model|Mixin|Wizard|Adapter))\s*\(",
        re.MULTILINE,
    ),
    "PRIVATE_METHOD": re.compile(
        r"^def\s+_[a-zA-Z_]\w*\s*\(",  # def _foo(
        re.MULTILINE,
    ),
    "VERBATIM_METHOD_BODY": re.compile(
        r"^\s+(?:self\.env\[|return \w+\(|raise ValidationError|return request\.make_response|@http\.route)",
        re.MULTILINE,
    ),
    "VENDOR_SDK": re.compile(
        r"\b(?:vendor-A|target-ai-ext|comms-vendor|ext-ax|ext-iap-vendor|target-stack-internal|target-bank-ext)\b",
        re.IGNORECASE,
    ),
    "INTERNAL_HOST": re.compile(
        r"(?:localhost:[0-9]+|127\.0\.0\.1(?::[0-9]+)?|https?://[\w.-]+\.odoo\.com/?[\w./-]*|https?://[\w.-]+\.vendor-A\.com/?[\w./-]*)",
    ),
}


# Pastas que devem ser EXCLUÍDAS do scan (são docs canônicos gerados pelo sanitizer)
ALLOWLIST_FILES = {
    "README.md",  # gerado pelo sanitize.py
    "LICENSE.md",  # gerado pelo sanitize.py
    "SANITIZATION-MAP.md",  # gerado pelo sanitize.py (audit log)
}
ALLOWLIST_DIRS = {
    ".git",
}


class Violation(NamedTuple):
    file: str
    line_no: int
    pattern: str
    excerpt: str


def scan_file(path: pathlib.Path) -> list[Violation]:
    """Scan a single file for verbatim patterns."""
    violations: list[Violation] = []
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return violations

    for line_no, line in enumerate(text.splitlines(), start=1):
        for pattern_name, pattern in PATTERNS.items():
            if pattern.search(line):
                # Sanitize excerpt for display
                excerpt = line.strip()
                if len(excerpt) > 100:
                    excerpt = excerpt[:97] + "..."
                violations.append(
                    Violation(
                        file=path.name,
                        line_no=line_no,
                        pattern=pattern_name,
                        excerpt=excerpt,
                    )
                )
    return violations


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--package", required=True, help="Pacote consumer-facing (saída de sanitize.py)"
    )
    parser.add_argument("--json", action="store_true", help="Output em JSON")
    args = parser.parse_args()

    pkg = pathlib.Path(args.package)
    if not pkg.exists():
        print(f"❌ Pacote não encontrado: {pkg}", file=sys.stderr)
        return 1

    all_violations: list[Violation] = []
    files_scanned = 0

    for src in sorted(pkg.rglob("*")):
        if src.is_dir():
            # Skip allowlisted dirs
            if any(part in ALLOWLIST_DIRS for part in src.parts):
                continue
            continue
        if not src.is_file():
            continue
        if src.name in ALLOWLIST_FILES:
            # These are generated by sanitize.py, expected to mention the patterns
            # in DOC form (e.g., the SANITIZATION-MAP.md)
            continue
        rel = src.relative_to(pkg).as_posix()
        if any(part in ALLOWLIST_DIRS for part in src.parts):
            continue

        files_scanned += 1
        violations = scan_file(src)
        # Adjust file path to be relative
        for v in violations:
            all_violations.append(
                Violation(
                    file=rel,
                    line_no=v.line_no,
                    pattern=v.pattern,
                    excerpt=v.excerpt,
                )
            )

    if args.json:
        out = {
            "package": str(pkg),
            "files_scanned": files_scanned,
            "violations_total": len(all_violations),
            "violations": [v._asdict() for v in all_violations],
            "result": "CLEAN" if not all_violations else "VERBATIM_DETECTED",
        }
        print(json.dumps(out, indent=2, ensure_ascii=False))
        return 0 if not all_violations else 2

    print(f"=== Verifying package: {pkg} ===\n")
    print(f"  Files scanned: {files_scanned}")
    print(
        f"  Allowlisted:   {len(ALLOWLIST_FILES)} (README.md, LICENSE.md, SANITIZATION-MAP.md)"
    )
    print()

    if not all_violations:
        print(f"  ✅ PACOTE LIMPO — nenhum verbatim detectado")
        print(f"     Safe to deliver to consumer team.")
        return 0

    print(f"  ❌ VERBATIM DETECTADO — {len(all_violations)} violação(ões)")
    print()
    by_pattern: dict[str, int] = {}
    for v in all_violations:
        by_pattern[v.pattern] = by_pattern.get(v.pattern, 0) + 1
    for pat, count in sorted(by_pattern.items()):
        print(f"    {pat}: {count}")

    print()
    print("  Primeiras 5 violações (sample):")
    for v in all_violations[:5]:
        print(f"    [{v.pattern}] {v.file}:{v.line_no}")
        print(f"        {v.excerpt}")

    print()
    print(f"  ❌ RESULTADO: GATE FALHOU — NÃO distribuir a consumer team.")
    print(f"     Re-rodar: python3 sanitize.py --dissect <path> --output {pkg}")
    return 2


if __name__ == "__main__":
    sys.exit(main())
